# Makefile for kernel demo

TOOLS   = arm-none-eabi
AS      = $(TOOLS)-as
CC      = $(TOOLS)-gcc
LD      = $(TOOLS)-ld.bfd
OBJCOPY = $(TOOLS)-objcopy
DUMP    = $(TOOLS)-objdump -D
GDB     = $(TOOLS)-gdb
MKDIR_P = mkdir -p
CP      = cp
SYMLINK = lns -af

############### LIBRARY INCLUSION ######################

FLOAT           = soft
DEBUG           = 1

PROJ             = lab2
BUILD            = build
ASM              = asm
BIN              = bin

# Terminal color and modifier attributes. Make sure to handle when no terminal
# is connected.
# Return to the normal terminal colors
n := $(shell tty -s && tput sgr0)
# Red color
r := $(shell tty -s && tput setaf 1)
# Green color
g := $(shell tty -s && tput setaf 2)
# Green color
y := $(shell tty -s && tput setaf 3)
j := $(shell tty -s && tput setaf 5)
# Bold text
b := $(shell tty -s && tput bold)
# Underlined text
u := $(shell tty -s && tput smul)

# BIN INFO
HASH_PROJ 	= $(shell echo -n "$(DEBUG)$(OPTIMIZATION)$(FLOAT)" | md5sum | cut -d' ' -f1)
BIN_DIR     = $(BUILD)/$(BIN)
BINARY      = $(PROJ)_$(HASH_PROJ)

# KERNEL PROJ DIRS
ASM_DIR         			= $(ASM)
INC_DIR         			= include
LIB_DIR         			= lib
SRC_DIR         			= src
OBJ_DIR         			= $(BUILD)/$(PROJ)
OBJ_PROJ_DIR   				= $(OBJ_DIR)/$(PROJ)_$(HASH_PROJ)
PRE_BUILT_OBJ_DIR 			= $(BUILD)/prebuilt

# SRC FILES
C_SRC        	= $(wildcard $(SRC_DIR)/*.c)
ASM_SRC        	= $(wildcard $(ASM_DIR)/*.S)

# RULES
K_OBJ_RULE        		= $(C_SRC:$(SRC_DIR)/%.c=$(OBJ_PROJ_DIR)/%.o)
ASM_SRC_RULE        	= $(ASM_SRC:$(ASM_DIR)/%.S=$(OBJ_PROJ_DIR)/%.o)

# OBJECTS
OBJECTS        			= $(wildcard $(OBJ_PROJ_DIR)/*.o)
PRE_BUILT_OBJECTS 		= $(wildcard $(PRE_BUILT_OBJ_DIR)/*.o)

# Final output
OUTPUT = $(BIN_DIR)/$(BINARY)

# Path to soft float lib
ifeq ($(FLOAT), soft)
	FLOAT_ARCH += -mfloat-abi=softfp
else
	FLOAT_ARCH += -mfloat-abi=hard -mfpu=fpv4-sp-d16  -march=armv7e-m
endif

# DEBUGGING is enabled by default, you can reduce binary size by disabling the
# DEBUGGING
ifeq ($(DEBUG), 1)
	DEFINE_MACROS = -DDEBUG -g
	OPTIMIZATION = -O0
else
	OPTIMIZATION = -O3 -funroll-all-loops
endif

ARCH                 = $(ARG) $(FLOAT_ARCH) -mslow-flash-data -mcpu=cortex-m4 -mlittle-endian -mthumb
COMPILER_ERROR_FLAGS = -std=gnu99 -Wall -Werror -Wshadow -Wextra -Wunused
CCFLAGS              = $(ARCH) $(COMPILER_ERROR_FLAGS) $(OPTIMIZATION) $(DEFINE_MACROS)

########################################################

################### ROOT RULES #########################
.PHONY: help setup flash doc clean veryclean $(BIN_DIR)/$(BINARY).elf
.SILENT:setup flash
# COMMENT LINE FOR VERBOSE LINKING
.SILENT:$(BIN_DIR)/$(BINARY).elf

help:
	@printf "$b18-349 Makefile Usage:$n\n"
	@printf "\n"
	@printf "$bTargets:$n\n"
	@printf "\t$bbuild$n\n"
	@printf "\t    Compiles and links the specified $bPROJ$n.\n"
	@printf "\n"
	@printf "\t$bflash$n\n"
	@printf "\t    Compile, link and upload binary to board over serial.\n"
	@printf "\t    Be sure to run $bwindow_ocd.batch$n if you are in windows.\n"
	@printf "\t    Be sure to run $b./linux.ocd$n if you are in linux/mac.\n"
	@printf "\n"
	@printf "\t$bview-dump$n\n"
	@printf "\t    Compile, link and show disassembled binary.\n"
	@printf "\n"
	@printf "\t$bdoc$n\n"
	@printf "\t    Builds doxygen and ouputs into $bdoxygen_docs$n.\n"
	@printf "\t    Check $bdoxygen.warn$n for errors\n"
	@printf "\n"
	@printf "\t$bclean$n\n"
	@printf "\t    Cleans up all of the files generated by compilation in the\n"
	@printf "\t    $b$(BUILD)$n directory.\n"
	@printf "\n"
	@printf "\t$bcleandoc$n\n"
	@printf "\t    Cleans up generated doxygen files\n"
	@printf "\n"
	@printf "$bVariables:$n\n"
	@printf "\t$bPROJ$n\n"
	@printf "\t    The code to run in supervisor mode.\n"
	@printf "\n"
	@printf "\t$bOPTIMIZATION$n\n"
	@printf "\t    Sets the optimization level eg - $b-O3/-Os$n\n"
	@printf "\n"
	@printf "\t$bFLOAT$n\n"
	@printf "\t    Use soft or hard floating point libraries\n"
	@printf "\n"
	@printf "$bExamples:$n\n"
	@printf "\tmake build\n"
	@printf "\tmake flash\n"

compile: $(BIN_DIR)/$(BINARY).bin
	@printf "\n$y$bBuilt PROJ=$(PROJ) with FLOAT=$(FLOAT), DEBUG=$(DEBUG), OPTIMIZATION=$(OPTIMIZATION)\n$n$n"

setup:
	$(MKDIR_P) $(BUILD)
	$(MKDIR_P) $(BIN_DIR)
	$(MKDIR_P) $(OBJ_DIR)
	$(MKDIR_P) $(OBJ_PROJ_DIR)

build : setup compile

flash:	build
	cp util/init_template.nc /tmp/init.nc
	sed -i -e 's|<template>|$(BINARY)|g' /tmp/init.nc
	cp util/init_template.gdb /tmp/init.gdb
	sed -i -e 's|<template>|$(BINARY)|g' /tmp/init.gdb
	@printf "\n"
	@printf "$y***************************************************************\n$n"
	@printf "$yFlashing $(BINARY) to board...\n$n"
	@printf "$y***************************************************************\n$n"
	cat /tmp/init.nc | nc localhost 4444
	@printf "Opening GDB...\n"
	$(GDB) -x /tmp/init.gdb

view-dump: build dump

dump:
	$(DUMP) $(BIN_DIR)/$(BINARY).elf | less

########################################################

################# COMPILATION RULES ####################

$(OBJ_PROJ_DIR)/%.o: $(SRC_DIR)/%.c
	@printf "\n$b$yCompiling: $<$n$n\n" $<
	$(CC) -I$(INC_DIR) $(CCFLAGS) -c $< -o $@

$(OBJ_PROJ_DIR)/%.o: $(ASM_DIR)/%.S
	@printf "\n$y$bAssembling: $<$n$n\n"
	$(AS) $< -o $@

$(FREERTOS_OBJ_PROJ_DIR)/%.o: $(FREERTOS_SRC_DIR)/%.c
	@printf "\n$b$yCompiling: $<$n$n\n" $<
	$(CC) -I$(INC_DIR) $(CCFLAGS) -c $< -o $@

########################################################

################### BINARY RULES #######################

$(BIN_DIR)/$(BINARY).bin:	$(BIN_DIR)/$(BINARY).elf
	@printf "\n$y$bCreating $(BINARY) binary file...$n$n\n"
	$(OBJCOPY) $(BIN_DIR)/$(BINARY).elf $(BIN_DIR)/$(BINARY).bin -O binary

$(BIN_DIR)/$(BINARY).elf: $(K_OBJ_RULE) $(ASM_SRC_RULE)
	cp util/linker_template.lds /tmp/linker.lds
	@printf "\n$y$bLinking $(BINARY)...$n$n\n"
	$(LD) -T /tmp/linker.lds -o $(BIN_DIR)/$(BINARY).elf $(OBJECTS) $(PRE_BUILT_OBJECTS)

########################################################

################### CLEANING RULES #####################

clean:
	$(RM) $(BIN_DIR)/*
	$(RM) -r $(OBJ_DIR)/*

veryclean: clean
	$(RM) doxygen.warn
	$(RM) -r doxygen_docs

########################################################

################### DOC RULES #########################

doc:
	doxygen util/doxygen/Doxyfile

cleandoc:
	$(RM) doxygen.warn
	$(RM) -r doxygen_docs
